branch-defaults:
  eb:
    environment: AlacrityChallenge2-env
environment-defaults:
  AlacrityChallenge2-env:
    branch: null
    repository: null
global:
  application_name: alacrity_challenge_2
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: dist/app.zip
